"""initial

Revision ID: 43cabc872556
Revises:
Create Date: 2026-06-14 08:19:36.244960

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '43cabc872556'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataforge_catalog',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('connection_id', sa.String(length=64), nullable=False),
    sa.Column('schema_name', sa.String(length=200), nullable=False),
    sa.Column('table_name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('layer', sa.String(length=10), nullable=False),
    sa.Column('columns_json', sa.JSON(), nullable=False),
    sa.Column('primary_keys', sa.JSON(), nullable=False),
    sa.Column('foreign_keys', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('partition_columns', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('sensitivity', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('custom_properties', sa.JSON(), nullable=False),
    sa.Column('upstream_tables', sa.JSON(), nullable=False),
    sa.Column('downstream_tables', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_profiled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_catalog_connection', 'dataforge_catalog', ['connection_id'], unique=False)
    op.create_index('ix_catalog_layer', 'dataforge_catalog', ['layer'], unique=False)
    op.create_index('ix_catalog_table_name', 'dataforge_catalog', ['table_name'], unique=False)
    op.create_table('dataforge_connections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('db_type', sa.String(length=50), nullable=False),
    sa.Column('host', sa.String(length=500), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('database', sa.String(length=200), nullable=True),
    sa.Column('schema_name', sa.String(length=200), nullable=True),
    sa.Column('extra_params', sa.JSON(), nullable=False),
    sa.Column('use_ssl', sa.Boolean(), nullable=False),
    sa.Column('connection_timeout', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_connections_db_type', 'dataforge_connections', ['db_type'], unique=False)
    op.create_table('dataforge_lineage_nodes',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('node_type', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lineage_nodes_type', 'dataforge_lineage_nodes', ['node_type'], unique=False)
    op.create_table('dataforge_pipelines',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('failure_strategy', sa.String(length=30), nullable=False),
    sa.Column('notification_channels', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_pipelines_schedule', 'dataforge_pipelines', ['schedule_cron'], unique=False)
    op.create_table('dataforge_lineage_edges',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('edge_type', sa.String(length=50), nullable=False),
    sa.Column('transformation', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['dataforge_lineage_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['dataforge_lineage_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lineage_edges_source', 'dataforge_lineage_edges', ['source_id'], unique=False)
    op.create_index('ix_lineage_edges_target', 'dataforge_lineage_edges', ['target_id'], unique=False)
    op.create_table('dataforge_tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('pipeline_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_connection_id', sa.String(length=64), nullable=False),
    sa.Column('target_connection_id', sa.String(length=64), nullable=False),
    sa.Column('source_query', sa.Text(), nullable=False),
    sa.Column('target_table', sa.String(length=500), nullable=False),
    sa.Column('write_mode', sa.String(length=30), nullable=False),
    sa.Column('warehouse_layer', sa.String(length=10), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('retry_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['dataforge_pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_pipeline', 'dataforge_tasks', ['pipeline_id'], unique=False)
    op.create_table('dataforge_task_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('rows_written', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['dataforge_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_runs_status', 'dataforge_task_runs', ['status'], unique=False)
    op.create_index('ix_task_runs_task', 'dataforge_task_runs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_runs_task', table_name='dataforge_task_runs')
    op.drop_index('ix_task_runs_status', table_name='dataforge_task_runs')
    op.drop_table('dataforge_task_runs')
    op.drop_index('ix_tasks_pipeline', table_name='dataforge_tasks')
    op.drop_table('dataforge_tasks')
    op.drop_index('ix_lineage_edges_target', table_name='dataforge_lineage_edges')
    op.drop_index('ix_lineage_edges_source', table_name='dataforge_lineage_edges')
    op.drop_table('dataforge_lineage_edges')
    op.drop_index('ix_pipelines_schedule', table_name='dataforge_pipelines')
    op.drop_table('dataforge_pipelines')
    op.drop_index('ix_lineage_nodes_type', table_name='dataforge_lineage_nodes')
    op.drop_table('dataforge_lineage_nodes')
    op.drop_index('ix_connections_db_type', table_name='dataforge_connections')
    op.drop_table('dataforge_connections')
    op.drop_index('ix_catalog_table_name', table_name='dataforge_catalog')
    op.drop_index('ix_catalog_layer', table_name='dataforge_catalog')
    op.drop_index('ix_catalog_connection', table_name='dataforge_catalog')
    op.drop_table('dataforge_catalog')
    # ### end Alembic commands ###
