# -*- coding: utf-8 -*-
"""
DataForge AI - AI provider abstraction layer.

Provides a unified interface for interacting with multiple LLM backends
(OpenAI, Anthropic, local models, etc.) with built-in rate limiting,
automatic retry, token-usage tracking, and streaming support.
"""

from __future__ import annotations

import asyncio
import logging
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import (
    Any,
    AsyncIterator,
    Callable,
    Dict,
    List,
    Optional,
    Sequence,
    Union,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

class ModelProvider(str, Enum):
    """Supported AI model providers."""

    OPENAI = "openai"
    ANTHROPIC = "anthropic"
    AZURE_OPENAI = "azure_openai"
    LOCAL = "local"


@dataclass
class TokenUsage:
    """Tracks token consumption for a single request or accumulated usage.

    Attributes:
        prompt_tokens: Number of tokens in the prompt / input.
        completion_tokens: Number of tokens in the completion / output.
        total_tokens: Total tokens consumed (prompt + completion).
    """

    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0

    def __add__(self, other: "TokenUsage") -> "TokenUsage":
        return TokenUsage(
            prompt_tokens=self.prompt_tokens + other.prompt_tokens,
            completion_tokens=self.completion_tokens + other.completion_tokens,
            total_tokens=self.total_tokens + other.total_tokens,
        )


@dataclass
class ChatMessage:
    """A single message in a chat conversation.

    Attributes:
        role: The role of the message sender (system, user, assistant).
        content: The textual content of the message.
        name: Optional name identifier for the speaker.
    """

    role: str  # "system" | "user" | "assistant"
    content: str
    name: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Serialize the message to a plain dictionary."""
        payload: Dict[str, Any] = {"role": self.role, "content": self.content}
        if self.name:
            payload["name"] = self.name
        return payload


@dataclass
class AIResponse:
    """Unified response object returned by every provider.

    Attributes:
        content: The textual response generated by the model.
        model: The model identifier that produced the response.
        usage: Token consumption statistics for this request.
        finish_reason: The reason the model stopped generating (e.g. ``stop``,
            ``length``, ``content_filter``).
        raw: The raw provider-specific response payload, kept for debugging or
            advanced post-processing.
    """

    content: str
    model: str
    usage: TokenUsage
    finish_reason: Optional[str] = None
    raw: Optional[Any] = None


@dataclass
class StreamChunk:
    """A single chunk emitted during streaming generation.

    Attributes:
        delta: The incremental text produced in this chunk.
        finish_reason: Set when this chunk signals the end of generation.
        usage: Token usage, typically only populated in the final chunk.
    """

    delta: str = ""
    finish_reason: Optional[str] = None
    usage: Optional[TokenUsage] = None


@dataclass
class ProviderConfig:
    """Configuration bundle for an AI provider instance.

    Attributes:
        provider: Which provider backend to use.
        api_key: The API key (or ``None`` for local models).
        base_url: Optional custom base URL for the provider API.
        model: Default model identifier (e.g. ``gpt-4o``, ``claude-3-opus``).
        temperature: Sampling temperature controlling randomness.
        max_tokens: Maximum tokens to generate in a single response.
        timeout: Per-request timeout in seconds.
        max_retries: Number of automatic retries on transient failures.
        retry_delay: Base delay between retries in seconds (exponential back-off).
        rate_limit_rpm: Maximum requests per minute (``0`` = unlimited).
        rate_limit_tpm: Maximum tokens per minute (``0`` = unlimited).
        extra: Provider-specific keyword arguments forwarded to the client.
    """

    provider: ModelProvider = ModelProvider.OPENAI
    api_key: Optional[str] = None
    base_url: Optional[str] = None
    model: str = "gpt-4o"
    temperature: float = 0.2
    max_tokens: int = 4096
    timeout: float = 60.0
    max_retries: int = 3
    retry_delay: float = 1.0
    rate_limit_rpm: int = 60
    rate_limit_tpm: int = 100_000
    extra: Dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Rate limiter
# ---------------------------------------------------------------------------

class RateLimiter:
    """A simple sliding-window rate limiter for API calls.

    Enforces both requests-per-minute (RPM) and tokens-per-minute (TPM)
    limits using an in-memory sliding window.

    Args:
        rpm: Maximum requests per minute.  ``0`` disables RPM limiting.
        tpm: Maximum tokens per minute.  ``0`` disables TPM limiting.
    """

    def __init__(self, rpm: int = 0, tpm: int = 0) -> None:
        self._rpm = rpm
        self._tpm = tpm
        self._request_timestamps: List[float] = []
        self._token_records: List[tuple[float, int]] = []
        self._lock = asyncio.Lock()

    @staticmethod
    def _prune_window(records: List, window_seconds: float = 60.0) -> None:
        """Remove entries older than *window_seconds* from *records* in-place."""
        cutoff = time.monotonic() - window_seconds
        while records and records[0] < cutoff:
            records.pop(0)

    async def acquire(self, estimated_tokens: int = 0) -> None:
        """Block until the caller is allowed to proceed.

        Args:
            estimated_tokens: The estimated token cost of the upcoming request,
                used for TPM limiting.
        """
        async with self._lock:
            # --- RPM check ---
            if self._rpm > 0:
                self._prune_window(self._request_timestamps)
                while len(self._request_timestamps) >= self._rpm:
                    sleep_for = self._request_timestamps[0] - (time.monotonic() - 60.0)
                    if sleep_for > 0:
                        logger.debug("Rate limiter: sleeping %.2fs (RPM limit)", sleep_for)
                        await asyncio.sleep(sleep_for)
                    self._prune_window(self._request_timestamps)
                self._request_timestamps.append(time.monotonic())

            # --- TPM check ---
            if self._tpm > 0 and estimated_tokens > 0:
                self._prune_window(self._token_records)
                current_tpm = sum(t for _, t in self._token_records)
                while current_tpm + estimated_tokens > self._tpm:
                    sleep_for = self._token_records[0][0] - (time.monotonic() - 60.0)
                    if sleep_for > 0:
                        logger.debug("Rate limiter: sleeping %.2fs (TPM limit)", sleep_for)
                        await asyncio.sleep(sleep_for)
                    self._prune_window(self._token_records)
                    current_tpm = sum(t for _, t in self._token_records)
                self._token_records.append((time.monotonic(), estimated_tokens))

    def record_usage(self, tokens_used: int) -> None:
        """Record actual token consumption after a request completes.

        This is a fire-and-forget synchronous call; the records are consumed by
        the next ``acquire`` check.

        Args:
            tokens_used: The actual number of tokens consumed.
        """
        self._token_records.append((time.monotonic(), tokens_used))


# ---------------------------------------------------------------------------
# Abstract base provider
# ---------------------------------------------------------------------------

class BaseAIProvider(ABC):
    """Abstract base class that every AI provider must implement.

    Subclasses are responsible for translating the unified interface into
    provider-specific API calls and mapping responses back to ``AIResponse``
    and ``StreamChunk`` objects.
    """

    def __init__(self, config: ProviderConfig) -> None:
        self._config = config
        self._cumulative_usage = TokenUsage()
        self._rate_limiter = RateLimiter(
            rpm=config.rate_limit_rpm,
            tpm=config.rate_limit_tpm,
        )
        self._request_count: int = 0

    # -- Properties ---------------------------------------------------------

    @property
    def config(self) -> ProviderConfig:
        """Return the active provider configuration."""
        return self._config

    @property
    def cumulative_usage(self) -> TokenUsage:
        """Return cumulative token usage since this provider was created."""
        return self._cumulative_usage

    @property
    def request_count(self) -> int:
        """Return total number of requests made through this provider."""
        return self._request_count

    # -- Abstract interface -------------------------------------------------

    @abstractmethod
    async def generate(
        self,
        prompt: str,
        *,
        system: Optional[str] = None,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
        stop: Optional[Sequence[str]] = None,
        **kwargs: Any,
    ) -> AIResponse:
        """Generate a completion from a single prompt string.

        Args:
            prompt: The user prompt.
            system: Optional system-level instruction prepended to the request.
            temperature: Override the default sampling temperature.
            max_tokens: Override the default maximum output tokens.
            stop: Optional sequence of stop strings.
            **kwargs: Provider-specific parameters.

        Returns:
            AIResponse with the generated text and metadata.
        """

    @abstractmethod
    async def chat(
        self,
        messages: List[ChatMessage],
        *,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
        stop: Optional[Sequence[str]] = None,
        **kwargs: Any,
    ) -> AIResponse:
        """Generate a completion from a multi-turn chat conversation.

        Args:
            messages: Ordered list of ``ChatMessage`` objects representing the
                conversation history.
            temperature: Override the default sampling temperature.
            max_tokens: Override the default maximum output tokens.
            stop: Optional sequence of stop strings.
            **kwargs: Provider-specific parameters.

        Returns:
            AIResponse with the generated text and metadata.
        """

    @abstractmethod
    async def complete(
        self,
        prompt: str,
        suffix: Optional[str] = None,
        *,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
        stop: Optional[Sequence[str]] = None,
        **kwargs: Any,
    ) -> AIResponse:
        """Perform a raw text completion (insert / fill-in-the-middle).

        This is useful for code-completion style tasks where both a prefix and
        a suffix surround the gap to be filled.

        Args:
            prompt: The text *before* the gap.
            suffix: Optional text *after* the gap.
            temperature: Override the default sampling temperature.
            max_tokens: Override the default maximum output tokens.
            stop: Optional sequence of stop strings.
            **kwargs: Provider-specific parameters.

        Returns:
            AIResponse with the generated text and metadata.
        """

    @abstractmethod
    async def stream_generate(
        self,
        prompt: str,
        *,
        system: Optional[str] = None,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
        **kwargs: Any,
    ) -> AsyncIterator[StreamChunk]:
        """Stream a completion from a single prompt, yielding chunks.

        Args:
            prompt: The user prompt.
            system: Optional system-level instruction.
            temperature: Override the default sampling temperature.
            max_tokens: Override the default maximum output tokens.
            **kwargs: Provider-specific parameters.

        Yields:
            StreamChunk objects as they arrive from the provider.
        """

    @abstractmethod
    async def stream_chat(
        self,
        messages: List[ChatMessage],
        *,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
        **kwargs: Any,
    ) -> AsyncIterator[StreamChunk]:
        """Stream a chat completion, yielding chunks.

        Args:
            messages: The conversation messages.
            temperature: Override the default sampling temperature.
            max_tokens: Override the default maximum output tokens.
            **kwargs: Provider-specific parameters.

        Yields:
            StreamChunk objects as they arrive from the provider.
        """

    # -- Shared helpers -----------------------------------------------------

    def _record_usage(self, usage: TokenUsage) -> None:
        """Accumulate token usage and increment the request counter."""
        self._cumulative_usage = self._cumulative_usage + usage
        self._request_count += 1

    async def _retry_with_backoff(
        self,
        fn: Callable[..., Any],
        *args: Any,
        **kwargs: Any,
    ) -> Any:
        """Execute *fn* with exponential-backoff retry logic.

        Args:
            fn: An async callable to execute.
            *args: Positional arguments forwarded to *fn*.
            **kwargs: Keyword arguments forwarded to *fn*.

        Returns:
            The return value of *fn*.

        Raises:
            Exception: The last exception if all retries are exhausted.
        """
        last_exc: Optional[Exception] = None
        for attempt in range(1, self._config.max_retries + 1):
            try:
                return await fn(*args, **kwargs)
            except Exception as exc:
                last_exc = exc
                delay = self._config.retry_delay * (2 ** (attempt - 1))
                logger.warning(
                    "Provider call failed (attempt %d/%d): %s  -- retrying in %.1fs",
                    attempt,
                    self._config.max_retries,
                    exc,
                    delay,
                )
                await asyncio.sleep(delay)
        raise last_exc  # type: ignore[misc]


# ---------------------------------------------------------------------------
# OpenAI provider
# ---------------------------------------------------------------------------

class OpenAIProvider(BaseAIProvider):
    """AI provider implementation backed by the OpenAI Chat Completions API.

    This provider supports ``gpt-4o``, ``gpt-4o-mini``, ``gpt-4-turbo``,
    ``o1-*`` reasoning models, and any other model accessible through the
    OpenAI-compatible API (including Azure OpenAI and self-hosted proxies
    like vLLM or LiteLLM by setting ``base_url``).

    Args:
        config: Provider configuration.  ``provider`` is ignored since this
            class is hard-coded to OpenAI.
    """

    def __init__(self, config: ProviderConfig) -> None:
        super().__init__(config)
        self._client: Any = None  # Lazy-initialized openai.AsyncOpenAI

    def _get_client(self) -> Any:
        """Lazily create and cache the ``openai.AsyncOpenAI`` client."""
        if self._client is None:
            try:
                from openai import AsyncOpenAI
            except ImportError as exc:
                raise ImportError(
                    "The 'openai' package is required for OpenAIProvider.  "
                    "Install it with:  pip install openai>=1.0"
                ) from exc

            client_kwargs: Dict[str, Any] = {}
            if self._config.api_key:
                client_kwargs["api_key"] = self._config.api_key
            if self._config.base_url:
                client_kwargs["base_url"] = self._config.base_url
            client_kwargs["timeout"] = self._config.timeout

            self._client = AsyncOpenAI(**client_kwargs)
        return self._client

    def _build_params(
        self,
        *,
        messages: List[Dict[str, Any]],
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
        stop: Optional[Sequence[str]] = None,
        stream: bool = False,
        **extra: Any,
    ) -> Dict[str, Any]:
        """Assemble the parameter dict for ``client.chat.completions.create``."""
        params: Dict[str, Any] = {
            "model": self._config.model,
            "messages": messages,
            "temperature": temperature if temperature is not None else self._config.temperature,
            "max_tokens": max_tokens if max_tokens is not None else self._config.max_tokens,
            "stream": stream,
        }
        if stop:
            params["stop"] = list(stop)
        params.update(extra)
        return params

    @staticmethod
    def _parse_response(response: Any) -> AIResponse:
        """Convert an OpenAI ``ChatCompletion`` object to ``AIResponse``."""
        choice = response.choices[0]
        usage_data = response.usage
        usage = TokenUsage(
            prompt_tokens=getattr(usage_data, "prompt_tokens", 0),
            completion_tokens=getattr(usage_data, "completion_tokens", 0),
            total_tokens=getattr(usage_data, "total_tokens", 0),
        )
        return AIResponse(
            content=choice.message.content or "",
            model=response.model,
            usage=usage,
            finish_reason=choice.finish_reason,
            raw=response,
        )

    # -- Core interface -----------------------------------------------------

    async def generate(
        self,
        prompt: str,
        *,
        system: Optional[str] = None,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
        stop: Optional[Sequence[str]] = None,
        **kwargs: Any,
    ) -> AIResponse:
        """Generate a completion from a single prompt string.

        Constructs a two-message conversation (system + user) and delegates
        to the OpenAI Chat Completions API.
        """
        messages: List[Dict[str, Any]] = []
        if system:
            messages.append({"role": "system", "content": system})
        messages.append({"role": "user", "content": prompt})

        async def _call() -> AIResponse:
            await self._rate_limiter.acquire(estimated_tokens=len(prompt) // 4)
            client = self._get_client()
            params = self._build_params(
                messages=messages,
                temperature=temperature,
                max_tokens=max_tokens,
                stop=stop,
                **kwargs,
            )
            response = await client.chat.completions.create(**params)
            ai_resp = self._parse_response(response)
            self._record_usage(ai_resp.usage)
            self._rate_limiter.record_usage(ai_resp.usage.total_tokens)
            return ai_resp

        return await self._retry_with_backoff(_call)

    async def chat(
        self,
        messages: List[ChatMessage],
        *,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
        stop: Optional[Sequence[str]] = None,
        **kwargs: Any,
    ) -> AIResponse:
        """Generate a completion from a multi-turn chat conversation."""
        raw_messages = [m.to_dict() for m in messages]

        async def _call() -> AIResponse:
            total_chars = sum(len(m.content) for m in messages)
            await self._rate_limiter.acquire(estimated_tokens=total_chars // 4)
            client = self._get_client()
            params = self._build_params(
                messages=raw_messages,
                temperature=temperature,
                max_tokens=max_tokens,
                stop=stop,
                **kwargs,
            )
            response = await client.chat.completions.create(**params)
            ai_resp = self._parse_response(response)
            self._record_usage(ai_resp.usage)
            self._rate_limiter.record_usage(ai_resp.usage.total_tokens)
            return ai_resp

        return await self._retry_with_backoff(_call)

    async def complete(
        self,
        prompt: str,
        suffix: Optional[str] = None,
        *,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
        stop: Optional[Sequence[str]] = None,
        **kwargs: Any,
    ) -> AIResponse:
        """Perform a fill-in-the-middle style completion.

        For models that do not natively support FIM, the prompt and suffix are
        concatenated into a single user message with a clear delimiter.
        """
        full_prompt = prompt
        if suffix:
            full_prompt = (
                f"{prompt}\n\n<|FIM_SUFFIX|>\n{suffix}\n\n<|FIM_MIDDLE|>\n"
            )
        return await self.generate(
            full_prompt,
            temperature=temperature,
            max_tokens=max_tokens,
            stop=stop,
            **kwargs,
        )

    async def stream_generate(
        self,
        prompt: str,
        *,
        system: Optional[str] = None,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
        **kwargs: Any,
    ) -> AsyncIterator[StreamChunk]:
        """Stream a completion from a single prompt."""
        messages: List[Dict[str, Any]] = []
        if system:
            messages.append({"role": "system", "content": system})
        messages.append({"role": "user", "content": prompt})

        await self._rate_limiter.acquire(estimated_tokens=len(prompt) // 4)
        client = self._get_client()
        params = self._build_params(
            messages=messages,
            temperature=temperature,
            max_tokens=max_tokens,
            stream=True,
            **kwargs,
        )
        stream = await client.chat.completions.create(**params)
        accumulated_tokens = 0

        async for raw_chunk in stream:
            if not raw_chunk.choices:
                continue
            delta_obj = raw_chunk.choices[0].delta
            delta_text = getattr(delta_obj, "content", "") or ""
            finish = raw_chunk.choices[0].finish_reason
            accumulated_tokens += max(1, len(delta_text) // 4)

            chunk = StreamChunk(
                delta=delta_text,
                finish_reason=finish,
            )
            yield chunk

        # Record approximate usage after streaming completes
        approx_usage = TokenUsage(
            prompt_tokens=len(prompt) // 4,
            completion_tokens=accumulated_tokens,
            total_tokens=len(prompt) // 4 + accumulated_tokens,
        )
        self._record_usage(approx_usage)

    async def stream_chat(
        self,
        messages: List[ChatMessage],
        *,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
        **kwargs: Any,
    ) -> AsyncIterator[StreamChunk]:
        """Stream a chat completion, yielding chunks."""
        raw_messages = [m.to_dict() for m in messages]
        total_chars = sum(len(m.content) for m in messages)

        await self._rate_limiter.acquire(estimated_tokens=total_chars // 4)
        client = self._get_client()
        params = self._build_params(
            messages=raw_messages,
            temperature=temperature,
            max_tokens=max_tokens,
            stream=True,
            **kwargs,
        )
        stream = await client.chat.completions.create(**params)
        accumulated_tokens = 0

        async for raw_chunk in stream:
            if not raw_chunk.choices:
                continue
            delta_obj = raw_chunk.choices[0].delta
            delta_text = getattr(delta_obj, "content", "") or ""
            finish = raw_chunk.choices[0].finish_reason
            accumulated_tokens += max(1, len(delta_text) // 4)

            yield StreamChunk(delta=delta_text, finish_reason=finish)

        approx_usage = TokenUsage(
            prompt_tokens=total_chars // 4,
            completion_tokens=accumulated_tokens,
            total_tokens=total_chars // 4 + accumulated_tokens,
        )
        self._record_usage(approx_usage)


# ---------------------------------------------------------------------------
# Anthropic provider (placeholder)
# ---------------------------------------------------------------------------

class AnthropicProvider(BaseAIProvider):
    """AI provider implementation for Anthropic Claude models.

    .. note::
        This is a **placeholder** implementation.  A full integration with
        the Anthropic Messages API will be provided in a future release.
    """

    async def generate(self, prompt: str, **kwargs: Any) -> AIResponse:
        raise NotImplementedError("AnthropicProvider is not yet implemented.")

    async def chat(self, messages: List[ChatMessage], **kwargs: Any) -> AIResponse:
        raise NotImplementedError("AnthropicProvider is not yet implemented.")

    async def complete(self, prompt: str, suffix: Optional[str] = None, **kwargs: Any) -> AIResponse:
        raise NotImplementedError("AnthropicProvider is not yet implemented.")

    async def stream_generate(self, prompt: str, **kwargs: Any) -> AsyncIterator[StreamChunk]:
        raise NotImplementedError("AnthropicProvider is not yet implemented.")
        yield  # Make this an async generator  # pragma: no cover

    async def stream_chat(self, messages: List[ChatMessage], **kwargs: Any) -> AsyncIterator[StreamChunk]:
        raise NotImplementedError("AnthropicProvider is not yet implemented.")
        yield  # pragma: no cover


# ---------------------------------------------------------------------------
# Provider factory
# ---------------------------------------------------------------------------

class AIProviderFactory:
    """Factory for creating AI provider instances from configuration.

    Usage::

        config = ProviderConfig(provider=ModelProvider.OPENAI, api_key="sk-...")
        provider = AIProviderFactory.create(config)
        response = await provider.generate("Write a SQL query to count users.")
    """

    _registry: Dict[ModelProvider, type] = {
        ModelProvider.OPENAI: OpenAIProvider,
        ModelProvider.ANTHROPIC: AnthropicProvider,
    }

    @classmethod
    def create(cls, config: ProviderConfig) -> BaseAIProvider:
        """Instantiate and return the appropriate provider.

        Args:
            config: Provider configuration specifying which backend to use.

        Returns:
            A concrete ``BaseAIProvider`` subclass instance.

        Raises:
            ValueError: If the requested provider is not registered.
        """
        provider_cls = cls._registry.get(config.provider)
        if provider_cls is None:
            raise ValueError(
                f"Unsupported AI provider: {config.provider.value}.  "
                f"Registered providers: {list(cls._registry.keys())}"
            )
        return provider_cls(config)

    @classmethod
    def register(cls, provider: ModelProvider, provider_cls: type) -> None:
        """Register a custom provider class.

        Args:
            provider: The enum value to associate with the class.
            provider_cls: A ``BaseAIProvider`` subclass.
        """
        cls._registry[provider] = provider_cls
