"""
DataForge AI - AI provider abstraction layer (LangChain edition).

Provides a unified interface for interacting with multiple LLM backends
(OpenAI, Azure OpenAI, Ollama, Tongyi/通义千问, DeepSeek, etc.) via
LangChain's ``BaseChatModel`` abstraction.  Includes built-in rate limiting,
automatic retry, token-usage tracking, and streaming support.

Backward-compatible: the original data models (``TokenUsage``, ``ChatMessage``,
``AIResponse``, ``StreamChunk``, ``ProviderConfig``) and the ``BaseAIProvider``
abstract interface are preserved so that existing callers do not need to change.
"""

from __future__ import annotations

import asyncio
import logging
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import StrEnum
from typing import (
    TYPE_CHECKING,
    Any,
    ClassVar,
)

from langchain_core.callbacks import BaseCallbackHandler
from langchain_core.messages import (
    AIMessage,
    BaseMessage,
    HumanMessage,
    SystemMessage,
)

if TYPE_CHECKING:
    from collections.abc import AsyncIterator, Callable, Sequence

    from langchain_core.language_models.chat_models import BaseChatModel
    from langchain_core.outputs import LLMResult

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

class ModelProvider(StrEnum):
    """Supported AI model providers."""

    OPENAI = "openai"
    ANTHROPIC = "anthropic"
    AZURE_OPENAI = "azure_openai"
    LOCAL = "local"
    OLLAMA = "ollama"
    TONGYI = "tongyi"
    DEEPSEEK = "deepseek"


@dataclass
class TokenUsage:
    """Tracks token consumption for a single request or accumulated usage.

    Attributes:
        prompt_tokens: Number of tokens in the prompt / input.
        completion_tokens: Number of tokens in the completion / output.
        total_tokens: Total tokens consumed (prompt + completion).
    """

    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0

    def __add__(self, other: TokenUsage) -> TokenUsage:
        return TokenUsage(
            prompt_tokens=self.prompt_tokens + other.prompt_tokens,
            completion_tokens=self.completion_tokens + other.completion_tokens,
            total_tokens=self.total_tokens + other.total_tokens,
        )


@dataclass
class ChatMessage:
    """A single message in a chat conversation.

    Attributes:
        role: The role of the message sender (system, user, assistant).
        content: The textual content of the message.
        name: Optional name identifier for the speaker.
    """

    role: str  # "system" | "user" | "assistant"
    content: str
    name: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize the message to a plain dictionary."""
        payload: dict[str, Any] = {"role": self.role, "content": self.content}
        if self.name:
            payload["name"] = self.name
        return payload

    def to_langchain_message(self) -> BaseMessage:
        """Convert to the corresponding LangChain message type."""
        if self.role == "system":
            return SystemMessage(content=self.content)
        if self.role == "assistant":
            return AIMessage(content=self.content)
        # Default: treat as human / user message
        return HumanMessage(content=self.content)


@dataclass
class AIResponse:
    """Unified response object returned by every provider.

    Attributes:
        content: The textual response generated by the model.
        model: The model identifier that produced the response.
        usage: Token consumption statistics for this request.
        finish_reason: The reason the model stopped generating (e.g. ``stop``,
            ``length``, ``content_filter``).
        raw: The raw provider-specific response payload, kept for debugging or
            advanced post-processing.
    """

    content: str
    model: str
    usage: TokenUsage
    finish_reason: str | None = None
    raw: Any | None = None


@dataclass
class StreamChunk:
    """A single chunk emitted during streaming generation.

    Attributes:
        delta: The incremental text produced in this chunk.
        finish_reason: Set when this chunk signals the end of generation.
        usage: Token usage, typically only populated in the final chunk.
    """

    delta: str = ""
    finish_reason: str | None = None
    usage: TokenUsage | None = None


@dataclass
class ProviderConfig:
    """Configuration bundle for an AI provider instance.

    Attributes:
        provider: Which provider backend to use.
        api_key: The API key (or ``None`` for local models).
        base_url: Optional custom base URL for the provider API.
        model: Default model identifier (e.g. ``gpt-4o``, ``claude-3-opus``).
        temperature: Sampling temperature controlling randomness.
        max_tokens: Maximum tokens to generate in a single response.
        timeout: Per-request timeout in seconds.
        max_retries: Number of automatic retries on transient failures.
        retry_delay: Base delay between retries in seconds (exponential back-off).
        rate_limit_rpm: Maximum requests per minute (``0`` = unlimited).
        rate_limit_tpm: Maximum tokens per minute (``0`` = unlimited).
        extra: Provider-specific keyword arguments forwarded to the client.
    """

    provider: ModelProvider = ModelProvider.OPENAI
    api_key: str | None = None
    base_url: str | None = None
    model: str = "gpt-4o"
    temperature: float = 0.2
    max_tokens: int = 4096
    timeout: float = 60.0
    max_retries: int = 3
    retry_delay: float = 1.0
    rate_limit_rpm: int = 60
    rate_limit_tpm: int = 100_000
    extra: dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Rate limiter
# ---------------------------------------------------------------------------

class RateLimiter:
    """A simple sliding-window rate limiter for API calls.

    Enforces both requests-per-minute (RPM) and tokens-per-minute (TPM)
    limits using an in-memory sliding window.

    Args:
        rpm: Maximum requests per minute.  ``0`` disables RPM limiting.
        tpm: Maximum tokens per minute.  ``0`` disables TPM limiting.
    """

    def __init__(self, rpm: int = 0, tpm: int = 0) -> None:
        self._rpm = rpm
        self._tpm = tpm
        self._request_timestamps: list[float] = []
        self._token_records: list[tuple[float, int]] = []
        self._lock = asyncio.Lock()

    @staticmethod
    def _prune_window(records: list, window_seconds: float = 60.0) -> None:
        """Remove entries older than *window_seconds* from *records* in-place."""
        cutoff = time.monotonic() - window_seconds
        while records and records[0] < cutoff:
            records.pop(0)

    async def acquire(self, estimated_tokens: int = 0) -> None:
        """Block until the caller is allowed to proceed.

        Args:
            estimated_tokens: The estimated token cost of the upcoming request,
                used for TPM limiting.
        """
        async with self._lock:
            # --- RPM check ---
            if self._rpm > 0:
                self._prune_window(self._request_timestamps)
                while len(self._request_timestamps) >= self._rpm:
                    sleep_for = self._request_timestamps[0] - (time.monotonic() - 60.0)
                    if sleep_for > 0:
                        logger.debug("Rate limiter: sleeping %.2fs (RPM limit)", sleep_for)
                        await asyncio.sleep(sleep_for)
                    self._prune_window(self._request_timestamps)
                self._request_timestamps.append(time.monotonic())

            # --- TPM check ---
            if self._tpm > 0 and estimated_tokens > 0:
                self._prune_window(self._token_records)
                current_tpm = sum(t for _, t in self._token_records)
                while current_tpm + estimated_tokens > self._tpm:
                    sleep_for = self._token_records[0][0] - (time.monotonic() - 60.0)
                    if sleep_for > 0:
                        logger.debug("Rate limiter: sleeping %.2fs (TPM limit)", sleep_for)
                        await asyncio.sleep(sleep_for)
                    self._prune_window(self._token_records)
                    current_tpm = sum(t for _, t in self._token_records)
                self._token_records.append((time.monotonic(), estimated_tokens))

    def record_usage(self, tokens_used: int) -> None:
        """Record actual token consumption after a request completes.

        This is a fire-and-forget synchronous call; the records are consumed by
        the next ``acquire`` check.

        Args:
            tokens_used: The actual number of tokens consumed.
        """
        self._token_records.append((time.monotonic(), tokens_used))


# ---------------------------------------------------------------------------
# Token-usage callback handler
# ---------------------------------------------------------------------------

class TokenUsageCallbackHandler(BaseCallbackHandler):
    """LangChain callback handler that accumulates token usage across calls.

    Attach an instance to a ``LangChainProvider`` (or pass it directly to a
    LangChain model's ``callbacks`` list) to transparently track token
    consumption without inspecting raw responses.

    Attributes:
        total_usage: Cumulative ``TokenUsage`` across all observed LLM calls.
        last_usage: ``TokenUsage`` from the most recent LLM call.
    """

    def __init__(self) -> None:
        super().__init__()
        self.total_usage = TokenUsage()
        self.last_usage = TokenUsage()

    # -- Synchronous callbacks ------------------------------------------------

    def on_llm_end(self, response: LLMResult, **kwargs: Any) -> None:
        """Called when a non-streaming LLM call finishes."""
        self._process_llm_result(response)

    def on_llm_error(self, error: BaseException, **kwargs: Any) -> None:
        """Called when an LLM call raises an error — nothing to record."""
        logger.debug("TokenUsageCallbackHandler: LLM error observed: %s", error)

    # -- Async callbacks ------------------------------------------------------

    async def on_llm_end_async(self, response: LLMResult, **kwargs: Any) -> None:
        """Async variant of ``on_llm_end``."""
        self._process_llm_result(response)

    # -- Internal helpers -----------------------------------------------------

    def _process_llm_result(self, response: LLMResult) -> None:
        """Extract token counts from an ``LLMResult`` and accumulate them."""
        prompt_tokens = 0
        completion_tokens = 0
        total_tokens = 0

        # LangChain stores token usage in llm_output (provider-specific key)
        llm_output = response.llm_output or {}
        token_usage_dict = llm_output.get("token_usage", llm_output.get("usage", {}))
        if isinstance(token_usage_dict, dict):
            prompt_tokens = token_usage_dict.get("prompt_tokens", 0)
            completion_tokens = token_usage_dict.get("completion_tokens", 0)
            total_tokens = token_usage_dict.get("total_tokens", 0)

        # Fallback: attempt to derive from generation info
        if total_tokens == 0:
            for generation_list in response.generations:
                for gen in generation_list:
                    gen_info = getattr(gen, "generation_info", {}) or {}
                    usage = gen_info.get("usage", {})
                    prompt_tokens += usage.get("prompt_tokens", 0)
                    completion_tokens += usage.get("completion_tokens", 0)
                    total_tokens += usage.get("total_tokens", 0)

        usage = TokenUsage(
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            total_tokens=total_tokens,
        )
        self.last_usage = usage
        self.total_usage = self.total_usage + usage

    def reset(self) -> None:
        """Reset all accumulated counters to zero."""
        self.total_usage = TokenUsage()
        self.last_usage = TokenUsage()


# ---------------------------------------------------------------------------
# Abstract base provider
# ---------------------------------------------------------------------------

class BaseAIProvider(ABC):
    """Abstract base class that every AI provider must implement.

    Subclasses are responsible for translating the unified interface into
    provider-specific API calls and mapping responses back to ``AIResponse``
    and ``StreamChunk`` objects.
    """

    def __init__(self, config: ProviderConfig) -> None:
        self._config = config
        self._cumulative_usage = TokenUsage()
        self._rate_limiter = RateLimiter(
            rpm=config.rate_limit_rpm,
            tpm=config.rate_limit_tpm,
        )
        self._request_count: int = 0

    # -- Properties ---------------------------------------------------------

    @property
    def config(self) -> ProviderConfig:
        """Return the active provider configuration."""
        return self._config

    @property
    def cumulative_usage(self) -> TokenUsage:
        """Return cumulative token usage since this provider was created."""
        return self._cumulative_usage

    @property
    def request_count(self) -> int:
        """Return total number of requests made through this provider."""
        return self._request_count

    # -- Abstract interface -------------------------------------------------

    @abstractmethod
    async def generate(
        self,
        prompt: str,
        *,
        system: str | None = None,
        temperature: float | None = None,
        max_tokens: int | None = None,
        stop: Sequence[str] | None = None,
        **kwargs: Any,
    ) -> AIResponse:
        """Generate a completion from a single prompt string.

        Args:
            prompt: The user prompt.
            system: Optional system-level instruction prepended to the request.
            temperature: Override the default sampling temperature.
            max_tokens: Override the default maximum output tokens.
            stop: Optional sequence of stop strings.
            **kwargs: Provider-specific parameters.

        Returns:
            AIResponse with the generated text and metadata.
        """

    @abstractmethod
    async def chat(
        self,
        messages: list[ChatMessage],
        *,
        temperature: float | None = None,
        max_tokens: int | None = None,
        stop: Sequence[str] | None = None,
        **kwargs: Any,
    ) -> AIResponse:
        """Generate a completion from a multi-turn chat conversation.

        Args:
            messages: Ordered list of ``ChatMessage`` objects representing the
                conversation history.
            temperature: Override the default sampling temperature.
            max_tokens: Override the default maximum output tokens.
            stop: Optional sequence of stop strings.
            **kwargs: Provider-specific parameters.

        Returns:
            AIResponse with the generated text and metadata.
        """

    @abstractmethod
    async def complete(
        self,
        prompt: str,
        suffix: str | None = None,
        *,
        temperature: float | None = None,
        max_tokens: int | None = None,
        stop: Sequence[str] | None = None,
        **kwargs: Any,
    ) -> AIResponse:
        """Perform a raw text completion (insert / fill-in-the-middle).

        This is useful for code-completion style tasks where both a prefix and
        a suffix surround the gap to be filled.

        Args:
            prompt: The text *before* the gap.
            suffix: Optional text *after* the gap.
            temperature: Override the default sampling temperature.
            max_tokens: Override the default maximum output tokens.
            stop: Optional sequence of stop strings.
            **kwargs: Provider-specific parameters.

        Returns:
            AIResponse with the generated text and metadata.
        """

    @abstractmethod
    async def stream_generate(
        self,
        prompt: str,
        *,
        system: str | None = None,
        temperature: float | None = None,
        max_tokens: int | None = None,
        **kwargs: Any,
    ) -> AsyncIterator[StreamChunk]:
        """Stream a completion from a single prompt, yielding chunks.

        Args:
            prompt: The user prompt.
            system: Optional system-level instruction.
            temperature: Override the default sampling temperature.
            max_tokens: Override the default maximum output tokens.
            **kwargs: Provider-specific parameters.

        Yields:
            StreamChunk objects as they arrive from the provider.
        """

    @abstractmethod
    async def stream_chat(
        self,
        messages: list[ChatMessage],
        *,
        temperature: float | None = None,
        max_tokens: int | None = None,
        **kwargs: Any,
    ) -> AsyncIterator[StreamChunk]:
        """Stream a chat completion, yielding chunks.

        Args:
            messages: The conversation messages.
            temperature: Override the default sampling temperature.
            max_tokens: Override the default maximum output tokens.
            **kwargs: Provider-specific parameters.

        Yields:
            StreamChunk objects as they arrive from the provider.
        """

    # -- Shared helpers -----------------------------------------------------

    def _record_usage(self, usage: TokenUsage) -> None:
        """Accumulate token usage and increment the request counter."""
        self._cumulative_usage = self._cumulative_usage + usage
        self._request_count += 1

    async def _retry_with_backoff(
        self,
        fn: Callable[..., Any],
        *args: Any,
        **kwargs: Any,
    ) -> Any:
        """Execute *fn* with exponential-backoff retry logic.

        Args:
            fn: An async callable to execute.
            *args: Positional arguments forwarded to *fn*.
            **kwargs: Keyword arguments forwarded to *fn*.

        Returns:
            The return value of *fn*.

        Raises:
            Exception: The last exception if all retries are exhausted.
        """
        last_exc: Exception | None = None
        for attempt in range(1, self._config.max_retries + 1):
            try:
                return await fn(*args, **kwargs)
            except Exception as exc:
                last_exc = exc
                delay = self._config.retry_delay * (2 ** (attempt - 1))
                logger.warning(
                    "Provider call failed (attempt %d/%d): %s  -- retrying in %.1fs",
                    attempt,
                    self._config.max_retries,
                    exc,
                    delay,
                )
                await asyncio.sleep(delay)
        raise last_exc  # type: ignore[misc]


# ---------------------------------------------------------------------------
# LLM factory — create LangChain ChatModel instances from config
# ---------------------------------------------------------------------------

class LLMFactory:
    """Factory for creating LangChain ``BaseChatModel`` instances.

    Translates a :class:`ProviderConfig` into the appropriate LangChain chat
    model class with the correct constructor arguments.

    Supported providers:
        * ``openai`` — :class:`langchain_openai.ChatOpenAI`
        * ``azure_openai`` — :class:`langchain_openai.AzureChatOpenAI`
        * ``ollama`` — :class:`langchain_community.chat_models.ChatOllama`
        * ``tongyi`` — :class:`langchain_community.chat_models.ChatTongyi`
        * ``deepseek`` — :class:`langchain_openai.ChatOpenAI` (OpenAI-compatible)

    Usage::

        config = ProviderConfig(provider=ModelProvider.OPENAI, api_key="sk-...")
        model = LLMFactory.create_chat_model(config)
        response = await model.ainvoke([HumanMessage(content="Hello")])
    """

    @staticmethod
    def create_chat_model(
        config: ProviderConfig,
        *,
        callbacks: list[BaseCallbackHandler] | None = None,
    ) -> BaseChatModel:
        """Instantiate and return a LangChain ``BaseChatModel``.

        Args:
            config: Provider configuration specifying which backend to use.
            callbacks: Optional list of LangChain callback handlers to attach
                to the model (e.g. for token-usage tracking).

        Returns:
            A configured ``BaseChatModel`` instance ready for ``invoke`` /
            ``ainvoke`` / ``stream`` / ``astream`` calls.

        Raises:
            ValueError: If the requested provider is not supported.
            ImportError: If the required LangChain integration package is not
                installed.
        """
        provider = config.provider
        common_kwargs: dict[str, Any] = {
            "temperature": config.temperature,
            "max_tokens": config.max_tokens,
            "request_timeout": config.timeout,
            "max_retries": config.max_retries,
        }
        if callbacks:
            common_kwargs["callbacks"] = callbacks

        # Merge any extra provider-specific kwargs
        common_kwargs.update(config.extra)

        if provider == ModelProvider.OPENAI:
            return LLMFactory._create_openai(config, common_kwargs)
        if provider == ModelProvider.AZURE_OPENAI:
            return LLMFactory._create_azure_openai(config, common_kwargs)
        if provider == ModelProvider.OLLAMA or provider == ModelProvider.LOCAL:
            return LLMFactory._create_ollama(config, common_kwargs)
        if provider == ModelProvider.TONGYI:
            return LLMFactory._create_tongyi(config, common_kwargs)
        if provider == ModelProvider.DEEPSEEK:
            return LLMFactory._create_deepseek(config, common_kwargs)

        raise ValueError(
            f"Unsupported provider: {provider.value}. "
            f"Supported providers: openai, azure_openai, ollama, local, tongyi, deepseek."
        )

    # -- Provider-specific constructors --------------------------------------

    @staticmethod
    def _create_openai(
        config: ProviderConfig,
        common_kwargs: dict[str, Any],
    ) -> BaseChatModel:
        """Create a :class:`ChatOpenAI` instance."""
        try:
            from langchain_openai import ChatOpenAI
        except ImportError as exc:
            raise ImportError(
                "langchain-openai is required for OpenAI support. "
                "Install it with:  pip install langchain-openai>=0.3.0"
            ) from exc

        kwargs: dict[str, Any] = {
            "model": config.model,
            **common_kwargs,
        }
        if config.api_key:
            kwargs["api_key"] = config.api_key
        if config.base_url:
            kwargs["base_url"] = config.base_url
        return ChatOpenAI(**kwargs)

    @staticmethod
    def _create_azure_openai(
        config: ProviderConfig,
        common_kwargs: dict[str, Any],
    ) -> BaseChatModel:
        """Create an :class:`AzureChatOpenAI` instance."""
        try:
            from langchain_openai import AzureChatOpenAI
        except ImportError as exc:
            raise ImportError(
                "langchain-openai is required for Azure OpenAI support. "
                "Install it with:  pip install langchain-openai>=0.3.0"
            ) from exc

        kwargs: dict[str, Any] = {
            "model": config.model,
            **common_kwargs,
        }
        if config.api_key:
            kwargs["api_key"] = config.api_key
        if config.base_url:
            kwargs["azure_endpoint"] = config.base_url
        # Azure-specific fields that may be supplied via extra
        if "azure_deployment" not in kwargs:
            kwargs["azure_deployment"] = config.model
        if "api_version" not in kwargs:
            kwargs["api_version"] = "2024-02-01"
        return AzureChatOpenAI(**kwargs)

    @staticmethod
    def _create_ollama(
        config: ProviderConfig,
        common_kwargs: dict[str, Any],
    ) -> BaseChatModel:
        """Create a :class:`ChatOllama` instance for local model inference."""
        try:
            from langchain_community.chat_models import ChatOllama
        except ImportError as exc:
            raise ImportError(
                "langchain-community is required for Ollama support. "
                "Install it with:  pip install langchain-community>=0.3.0"
            ) from exc

        # ChatOllama does not accept api_key or max_retries; filter them out
        ollama_kwargs = {
            k: v for k, v in common_kwargs.items()
            if k not in ("max_retries",)
        }
        return ChatOllama(
            model=config.model,
            base_url=config.base_url or "http://localhost:11434",
            **ollama_kwargs,
        )

    @staticmethod
    def _create_tongyi(
        config: ProviderConfig,
        common_kwargs: dict[str, Any],
    ) -> BaseChatModel:
        """Create a :class:`ChatTongyi` instance for Alibaba Tongyi (通义千问)."""
        try:
            from langchain_community.chat_models import ChatTongyi
        except ImportError as exc:
            raise ImportError(
                "langchain-community is required for Tongyi support. "
                "Install it with:  pip install langchain-community>=0.3.0"
            ) from exc

        kwargs: dict[str, Any] = {
            "model": config.model,
            **common_kwargs,
        }
        if config.api_key:
            kwargs["dashscope_api_key"] = config.api_key
        return ChatTongyi(**kwargs)

    @staticmethod
    def _create_deepseek(
        config: ProviderConfig,
        common_kwargs: dict[str, Any],
    ) -> BaseChatModel:
        """Create a :class:`ChatOpenAI` instance pointed at the DeepSeek API.

        DeepSeek exposes an OpenAI-compatible endpoint, so we reuse
        ``ChatOpenAI`` with the appropriate ``base_url``.
        """
        try:
            from langchain_openai import ChatOpenAI
        except ImportError as exc:
            raise ImportError(
                "langchain-openai is required for DeepSeek support. "
                "Install it with:  pip install langchain-openai>=0.3.0"
            ) from exc

        kwargs: dict[str, Any] = {
            "model": config.model,
            **common_kwargs,
        }
        if config.api_key:
            kwargs["api_key"] = config.api_key
        kwargs["base_url"] = config.base_url or "https://api.deepseek.com"
        return ChatOpenAI(**kwargs)


# ---------------------------------------------------------------------------
# LangChain-backed provider
# ---------------------------------------------------------------------------

class LangChainProvider(BaseAIProvider):
    """AI provider implementation backed by LangChain's ``BaseChatModel``.

    This is the primary provider for all supported LLM backends.  It delegates
    to the model created by :class:`LLMFactory` and uses LangChain's
    ``invoke`` / ``ainvoke`` / ``stream`` / ``astream`` methods under the hood.

    Token usage is tracked automatically via :class:`TokenUsageCallbackHandler`
    and merged into the provider-level cumulative counter.

    Args:
        config: Provider configuration specifying which backend to use.

    Example::

        config = ProviderConfig(
            provider=ModelProvider.OPENAI,
            api_key="sk-...",
            model="gpt-4o",
        )
        provider = LangChainProvider(config)
        response = await provider.generate("Write a SQL query to count users.")
        print(response.content)
    """

    def __init__(self, config: ProviderConfig) -> None:
        super().__init__(config)
        self._callback_handler = TokenUsageCallbackHandler()
        self._model: BaseChatModel | None = None

    @property
    def model(self) -> BaseChatModel:
        """Lazily create and return the underlying LangChain chat model."""
        if self._model is None:
            self._model = LLMFactory.create_chat_model(
                self._config,
                callbacks=[self._callback_handler],
            )
        return self._model

    @property
    def callback_handler(self) -> TokenUsageCallbackHandler:
        """Return the token-usage callback handler attached to this provider."""
        return self._callback_handler

    # -- Internal helpers -----------------------------------------------------

    @staticmethod
    def _build_messages(
        prompt: str,
        *,
        system: str | None = None,
    ) -> list[BaseMessage]:
        """Construct a LangChain message list from a single prompt string."""
        messages: list[BaseMessage] = []
        if system:
            messages.append(SystemMessage(content=system))
        messages.append(HumanMessage(content=prompt))
        return messages

    @staticmethod
    def _chat_messages_to_langchain(
        messages: list[ChatMessage],
    ) -> list[BaseMessage]:
        """Convert a list of :class:`ChatMessage` to LangChain message objects."""
        return [m.to_langchain_message() for m in messages]

    def _extract_usage_from_ai_message(self, ai_message: AIMessage) -> TokenUsage:
        """Extract token usage from an ``AIMessage``'s ``usage_metadata``.

        LangChain >= 0.3 attaches ``usage_metadata`` to ``AIMessage`` when the
        provider returns token counts.  Falls back to the callback handler's
        ``last_usage`` when metadata is unavailable.
        """
        usage_meta = getattr(ai_message, "usage_metadata", None)
        if usage_meta and isinstance(usage_meta, dict):
            return TokenUsage(
                prompt_tokens=usage_meta.get("input_tokens", 0),
                completion_tokens=usage_meta.get("output_tokens", 0),
                total_tokens=usage_meta.get("total_tokens", 0),
            )
        # Fallback: use the callback handler's last recorded usage
        return self._callback_handler.last_usage

    @staticmethod
    def _extract_finish_reason(ai_message: AIMessage) -> str | None:
        """Extract a finish-reason string from an ``AIMessage``."""
        response_metadata = getattr(ai_message, "response_metadata", {}) or {}
        # OpenAI-style
        finish = response_metadata.get("finish_reason")
        if finish:
            return finish
        # Some providers use "stop_reason"
        return response_metadata.get("stop_reason")

    def _build_model_overrides(
        self,
        *,
        temperature: float | None = None,
        max_tokens: int | None = None,
        stop: Sequence[str] | None = None,
    ) -> dict[str, Any]:
        """Build a dict of per-request model parameter overrides.

        These are forwarded to LangChain's ``invoke`` / ``stream`` via the
        model's ``bind`` mechanism or as config overrides.
        """
        overrides: dict[str, Any] = {}
        if temperature is not None:
            overrides["temperature"] = temperature
        if max_tokens is not None:
            overrides["max_tokens"] = max_tokens
        if stop is not None:
            overrides["stop"] = list(stop)
        return overrides

    def _get_effective_model(
        self,
        overrides: dict[str, Any],
    ) -> BaseChatModel:
        """Return the chat model, optionally bound with per-request overrides."""
        model = self.model
        if overrides:
            return model.bind(**overrides)
        return model

    # -- Core interface -------------------------------------------------------

    async def generate(
        self,
        prompt: str,
        *,
        system: str | None = None,
        temperature: float | None = None,
        max_tokens: int | None = None,
        stop: Sequence[str] | None = None,
        **kwargs: Any,
    ) -> AIResponse:
        """Generate a completion from a single prompt string.

        Constructs a system + user message pair and delegates to the LangChain
        chat model's ``ainvoke`` method.
        """
        lc_messages = self._build_messages(prompt, system=system)
        overrides = self._build_model_overrides(
            temperature=temperature,
            max_tokens=max_tokens,
            stop=stop,
        )

        async def _call() -> AIResponse:
            await self._rate_limiter.acquire(estimated_tokens=len(prompt) // 4)
            model = self._get_effective_model(overrides)
            ai_message: AIMessage = await model.ainvoke(lc_messages)
            usage = self._extract_usage_from_ai_message(ai_message)
            self._record_usage(usage)
            self._rate_limiter.record_usage(usage.total_tokens)
            return AIResponse(
                content=ai_message.content or "",
                model=self._config.model,
                usage=usage,
                finish_reason=self._extract_finish_reason(ai_message),
                raw=ai_message,
            )

        return await self._retry_with_backoff(_call)

    async def chat(
        self,
        messages: list[ChatMessage],
        *,
        temperature: float | None = None,
        max_tokens: int | None = None,
        stop: Sequence[str] | None = None,
        **kwargs: Any,
    ) -> AIResponse:
        """Generate a completion from a multi-turn chat conversation."""
        lc_messages = self._chat_messages_to_langchain(messages)
        overrides = self._build_model_overrides(
            temperature=temperature,
            max_tokens=max_tokens,
            stop=stop,
        )

        async def _call() -> AIResponse:
            total_chars = sum(len(m.content) for m in messages)
            await self._rate_limiter.acquire(estimated_tokens=total_chars // 4)
            model = self._get_effective_model(overrides)
            ai_message: AIMessage = await model.ainvoke(lc_messages)
            usage = self._extract_usage_from_ai_message(ai_message)
            self._record_usage(usage)
            self._rate_limiter.record_usage(usage.total_tokens)
            return AIResponse(
                content=ai_message.content or "",
                model=self._config.model,
                usage=usage,
                finish_reason=self._extract_finish_reason(ai_message),
                raw=ai_message,
            )

        return await self._retry_with_backoff(_call)

    async def complete(
        self,
        prompt: str,
        suffix: str | None = None,
        *,
        temperature: float | None = None,
        max_tokens: int | None = None,
        stop: Sequence[str] | None = None,
        **kwargs: Any,
    ) -> AIResponse:
        """Perform a fill-in-the-middle style completion.

        For models that do not natively support FIM, the prompt and suffix are
        concatenated into a single user message with a clear delimiter.
        """
        full_prompt = prompt
        if suffix:
            full_prompt = (
                f"{prompt}\n\n<|FIM_SUFFIX|>\n{suffix}\n\n<|FIM_MIDDLE|>\n"
            )
        return await self.generate(
            full_prompt,
            temperature=temperature,
            max_tokens=max_tokens,
            stop=stop,
            **kwargs,
        )

    async def stream_generate(
        self,
        prompt: str,
        *,
        system: str | None = None,
        temperature: float | None = None,
        max_tokens: int | None = None,
        **kwargs: Any,
    ) -> AsyncIterator[StreamChunk]:
        """Stream a completion from a single prompt, yielding chunks."""
        lc_messages = self._build_messages(prompt, system=system)
        overrides = self._build_model_overrides(
            temperature=temperature,
            max_tokens=max_tokens,
        )

        await self._rate_limiter.acquire(estimated_tokens=len(prompt) // 4)
        model = self._get_effective_model(overrides)

        accumulated_tokens = 0
        async for chunk in model.astream(lc_messages):
            delta_text = chunk.content if isinstance(chunk.content, str) else ""
            accumulated_tokens += max(1, len(delta_text) // 4) if delta_text else 0

            finish_reason: str | None = None
            response_metadata = getattr(chunk, "response_metadata", {}) or {}
            finish_reason = response_metadata.get("finish_reason")

            yield StreamChunk(
                delta=delta_text,
                finish_reason=finish_reason,
            )

        # Record approximate usage after streaming completes
        approx_usage = TokenUsage(
            prompt_tokens=len(prompt) // 4,
            completion_tokens=accumulated_tokens,
            total_tokens=len(prompt) // 4 + accumulated_tokens,
        )
        self._record_usage(approx_usage)

    async def stream_chat(
        self,
        messages: list[ChatMessage],
        *,
        temperature: float | None = None,
        max_tokens: int | None = None,
        **kwargs: Any,
    ) -> AsyncIterator[StreamChunk]:
        """Stream a chat completion, yielding chunks."""
        lc_messages = self._chat_messages_to_langchain(messages)
        overrides = self._build_model_overrides(
            temperature=temperature,
            max_tokens=max_tokens,
        )

        total_chars = sum(len(m.content) for m in messages)
        await self._rate_limiter.acquire(estimated_tokens=total_chars // 4)
        model = self._get_effective_model(overrides)

        accumulated_tokens = 0
        async for chunk in model.astream(lc_messages):
            delta_text = chunk.content if isinstance(chunk.content, str) else ""
            accumulated_tokens += max(1, len(delta_text) // 4) if delta_text else 0

            finish_reason: str | None = None
            response_metadata = getattr(chunk, "response_metadata", {}) or {}
            finish_reason = response_metadata.get("finish_reason")

            yield StreamChunk(
                delta=delta_text,
                finish_reason=finish_reason,
            )

        approx_usage = TokenUsage(
            prompt_tokens=total_chars // 4,
            completion_tokens=accumulated_tokens,
            total_tokens=total_chars // 4 + accumulated_tokens,
        )
        self._record_usage(approx_usage)


# ---------------------------------------------------------------------------
# OpenAI provider (backward-compatible alias)
# ---------------------------------------------------------------------------

class OpenAIProvider(LangChainProvider):
    """Backward-compatible alias for :class:`LangChainProvider` with the
    ``ModelProvider.OPENAI`` backend.

    Existing code that instantiates ``OpenAIProvider`` directly will continue
    to work without changes.

    Args:
        config: Provider configuration.  The ``provider`` field is forced to
            ``ModelProvider.OPENAI``.
    """

    def __init__(self, config: ProviderConfig) -> None:
        # Force provider type to OPENAI for backward compat
        config.provider = ModelProvider.OPENAI
        super().__init__(config)


# ---------------------------------------------------------------------------
# Anthropic provider (placeholder)
# ---------------------------------------------------------------------------

class AnthropicProvider(BaseAIProvider):
    """AI provider implementation for Anthropic Claude models.

    .. note::
        This is a **placeholder** implementation.  A full integration with
        the Anthropic Messages API will be provided in a future release.
    """

    async def generate(self, prompt: str, **kwargs: Any) -> AIResponse:
        raise NotImplementedError("AnthropicProvider is not yet implemented.")

    async def chat(self, messages: list[ChatMessage], **kwargs: Any) -> AIResponse:
        raise NotImplementedError("AnthropicProvider is not yet implemented.")

    async def complete(self, prompt: str, suffix: str | None = None, **kwargs: Any) -> AIResponse:
        raise NotImplementedError("AnthropicProvider is not yet implemented.")

    async def stream_generate(self, prompt: str, **kwargs: Any) -> AsyncIterator[StreamChunk]:
        raise NotImplementedError("AnthropicProvider is not yet implemented.")
        yield  # Make this an async generator  # pragma: no cover

    async def stream_chat(self, messages: list[ChatMessage], **kwargs: Any) -> AsyncIterator[StreamChunk]:
        raise NotImplementedError("AnthropicProvider is not yet implemented.")
        yield  # pragma: no cover


# ---------------------------------------------------------------------------
# Provider factory
# ---------------------------------------------------------------------------

class AIProviderFactory:
    """Factory for creating AI provider instances from configuration.

    By default all providers (except the Anthropic placeholder) are routed to
    :class:`LangChainProvider`, which uses LangChain's ``BaseChatModel`` under
    the hood.

    Usage::

        config = ProviderConfig(provider=ModelProvider.OPENAI, api_key="sk-...")
        provider = AIProviderFactory.create(config)
        response = await provider.generate("Write a SQL query to count users.")
    """

    _registry: ClassVar[dict[ModelProvider, type[BaseAIProvider]]] = {
        ModelProvider.OPENAI: LangChainProvider,
        ModelProvider.AZURE_OPENAI: LangChainProvider,
        ModelProvider.OLLAMA: LangChainProvider,
        ModelProvider.LOCAL: LangChainProvider,
        ModelProvider.TONGYI: LangChainProvider,
        ModelProvider.DEEPSEEK: LangChainProvider,
        ModelProvider.ANTHROPIC: AnthropicProvider,
    }

    @classmethod
    def create(cls, config: ProviderConfig) -> BaseAIProvider:
        """Instantiate and return the appropriate provider.

        Args:
            config: Provider configuration specifying which backend to use.

        Returns:
            A concrete ``BaseAIProvider`` subclass instance.

        Raises:
            ValueError: If the requested provider is not registered.
        """
        provider_cls = cls._registry.get(config.provider)
        if provider_cls is None:
            raise ValueError(
                f"Unsupported AI provider: {config.provider.value}.  "
                f"Registered providers: {list(cls._registry.keys())}"
            )
        return provider_cls(config)

    @classmethod
    def register(cls, provider: ModelProvider, provider_cls: type[BaseAIProvider]) -> None:
        """Register a custom provider class.

        Args:
            provider: The enum value to associate with the class.
            provider_cls: A ``BaseAIProvider`` subclass.
        """
        cls._registry[provider] = provider_cls
